---
- hosts: all
  sudo: yes
  roles:
    - PrabhuVignesh.consul_installer

- hosts: dbservers
  sudo: yes

  tasks:
  - name: Placing configuration file into the consul.d
    action: template src=template/consul.d/adaptdb.j2 dest=/etc/consul.d/db.json mode=0755
 
  - name: creating script file
    action: template src=template/scripts/agentrun.j2 dest=/tmp/agentrun.sh mode=0777

  - name: Starting consul agent in background process
    command: nohup /tmp/agentrun.sh
    async: 9999999999999
    poll: 0

- hosts: webservers
  sudo: yes

  tasks:
  - name: Placing configuration file into the consul.d
    action: template src=template/consul.d/adaptweb.j2 dest=/etc/consul.d/web.json mode=0755
 
  - name: creating script file
    action: template src=template/scripts/agentrun.j2 dest=/tmp/agentrun.sh mode=0777

  - name: Starting consul agent in background process
    command: nohup /tmp/agentrun.sh
    async: 9999999999999
    poll: 0

- hosts: cacheservers
  sudo: yes

  tasks:
  - name: Placing configuration file into the consul.d
    action: template src=template/consul.d/adaptcache.j2 dest=/etc/consul.d/cache.json mode=0755
 
  - name: creating script file
    action: template src=template/scripts/agentrun.j2 dest=/tmp/agentrun.sh mode=0777

  - name: Starting consul agent in background process
    command: nohup /tmp/agentrun.sh
    async: 9999999999999
    poll: 0